### ISSUE TITLE
ENOENT: no such file or directory error on running install seed start:dev tasks

### ISSUE THREAD

**Issue by antwake** [Fluidbyte/spaq#1]
Got this error when I first typed `devlab install seed start:dev `
_"ENOENT: no such file or directory, lstat '.yarn-cache/npm-core-js-2.4.1-4de911e667b0eae9124e34254b53aea6fc618d3e/client/'"._

the repo is here tho.

So I typed one task after the other

`devlab install`
`devlab seed`
`devlab start:dev`

and it worked.

Then I tried `devlab start` and I got this error _"unexpected token <" in bundle.js_ and nothing showed up at http://localhost:9999

**Comment by Fluidbyte** [comment]
Can you try running `devlab bundle start:dev` and see if that works? I'm not sure on the first error and am trying to replicate, but I think the second one is missing the webpack bundle.

**Comment by antwake** [comment]
oh yeah that was as simple as that :) I should have figured it out!

thanks  for the support

**Comment by Fluidbyte** [comment]
NP. It _should_ run `bundle` on `lab start:dev` as well, but if you hit it before webpack executes and completes on the first run it will bork.
